/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p2.matricula.vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import p2.matricula.controlador.MatriculaControlador;

/**
 *
 * @author Boris Perez
 */
public class MatriculaVista extends javax.swing.JFrame {
   
    // ListModel para asociarle al JList de los cursos matriculados
    private DefaultComboBoxModel<String> listModelCursosMatriculados;
    private DefaultComboBoxModel<String> listModelEstudiantes;
    private DefaultComboBoxModel<String> listModelProgramas;
    private DefaultComboBoxModel<String> listModelEstudiantesCurso;
    
    
    private MatriculaControlador controlador;
    
    /**
     * Creates new form MatriculaVista
     */
    public MatriculaVista() {
        listModelCursosMatriculados = new DefaultComboBoxModel<>();
        listModelEstudiantes = new DefaultComboBoxModel<>();
        listModelProgramas = new DefaultComboBoxModel<>();
        listModelEstudiantesCurso = new DefaultComboBoxModel<>();
        initComponents();
        
        controlador = new MatriculaControlador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoEstudiante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefonoEstudiante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreoEstudiante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPromedioEstudiante = new javax.swing.JTextField();
        btnRegEst = new javax.swing.JButton();
        btnCancelarEst = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtSemestreEstudiante = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbProgramaAcadRegCurso = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoCursoRegCurso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombreCursoRegCurso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRequisitoPromedioRegCurso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCapacidadRegCurso = new javax.swing.JTextField();
        btnCancelarCurso = new javax.swing.JButton();
        cmdRegCurso = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cmbCodigoEstudianteMatricula = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbCodigoCursoMatricula = new javax.swing.JComboBox<>();
        cmdMatricularCurso = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cmbProgramaMatricula = new javax.swing.JComboBox<>();
        cmdVerCursosEstudiante = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cmdAsignarNota = new javax.swing.JButton();
        cmbProgramaAsignarNota = new javax.swing.JComboBox<>();
        cmbCursoAsignarNota = new javax.swing.JComboBox<>();
        cmbEstudianteAsignarNota = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigoActualizarCurso = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRequisitoActualizarCurso = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCapacidadActualizarCurso = new javax.swing.JTextPane();
        cmdActualizarCurso = new javax.swing.JButton();
        cmbProgramasActualizar = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        txtLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCursos = new javax.swing.JList<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Código");

        jLabel2.setText("Nombres");

        jLabel3.setText("Teléfono");

        jLabel4.setText("Correo");

        jLabel5.setText("Promedio Acum.");

        btnRegEst.setText("Registrar");
        btnRegEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegEstActionPerformed(evt);
            }
        });

        btnCancelarEst.setText("Desactivar");
        btnCancelarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEstActionPerformed(evt);
            }
        });

        jLabel14.setText("Semestre");

        txtSemestreEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemestreEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnCancelarEst)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPromedioEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtCodigoEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtTelefonoEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtCorreoEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnRegEst, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSemestreEstudiante))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefonoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPromedioEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSemestreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEst)
                    .addComponent(btnRegEst))
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Programa Académico");

        cmbProgramaAcadRegCurso.setModel(listModelProgramas);
        cmbProgramaAcadRegCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProgramaAcadRegCursoActionPerformed(evt);
            }
        });

        jLabel8.setText("Código");

        jLabel9.setText("Nombre");

        jLabel10.setText("Requisito Prom.");

        jLabel11.setText("Capacidad");

        btnCancelarCurso.setText("Cancelar");
        btnCancelarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCursoActionPerformed(evt);
            }
        });

        cmdRegCurso.setText("Registrar");
        cmdRegCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancelarCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdRegCurso))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProgramaAcadRegCurso, 0, 138, Short.MAX_VALUE)
                            .addComponent(txtCodigoCursoRegCurso)
                            .addComponent(txtNombreCursoRegCurso)
                            .addComponent(txtRequisitoPromedioRegCurso)
                            .addComponent(txtCapacidadRegCurso))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbProgramaAcadRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoCursoRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreCursoRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRequisitoPromedioRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCapacidadRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdRegCurso)
                    .addComponent(btnCancelarCurso))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel6.setText("Estudiante");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Cód. Estudiante");

        cmbCodigoEstudianteMatricula.setModel(listModelEstudiantes);
        cmbCodigoEstudianteMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodigoEstudianteMatriculaActionPerformed(evt);
            }
        });

        jLabel13.setText("Cód. Curso");

        cmbCodigoCursoMatricula.setModel(listModelCursosMatriculados);
        cmbCodigoCursoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodigoCursoMatriculaActionPerformed(evt);
            }
        });

        cmdMatricularCurso.setText("Matricular");
        cmdMatricularCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMatricularCursoActionPerformed(evt);
            }
        });

        jLabel24.setText("Programa");

        cmbProgramaMatricula.setModel(listModelProgramas);
        cmbProgramaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProgramaMatriculaActionPerformed(evt);
            }
        });

        cmdVerCursosEstudiante.setText("Ver ->");
        cmdVerCursosEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerCursosEstudianteActionPerformed(evt);
            }
        });

        jButton1.setText("Retirar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31)
                        .addComponent(cmdMatricularCurso)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel24)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCodigoEstudianteMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCodigoCursoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbProgramaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdVerCursosEstudiante)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbCodigoEstudianteMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cmbProgramaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdVerCursosEstudiante))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCodigoCursoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdMatricularCurso)
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("Programa");

        jLabel21.setText("Curso");

        jLabel22.setText("Estudiante");

        jLabel23.setText("Nota");

        cmdAsignarNota.setText("Asignar");
        cmdAsignarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAsignarNotaActionPerformed(evt);
            }
        });

        cmbProgramaAsignarNota.setModel(listModelProgramas);

        cmbCursoAsignarNota.setModel(listModelCursosMatriculados);
        cmbCursoAsignarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoAsignarNotaActionPerformed(evt);
            }
        });

        cmbEstudianteAsignarNota.setModel(listModelEstudiantesCurso);

        jScrollPane5.setViewportView(txtNota);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCursoAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbProgramaAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEstudianteAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE))))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(cmdAsignarNota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbProgramaAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmbCursoAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmbEstudianteAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(cmdAsignarNota)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("Código");

        jLabel18.setText("Requisito");

        jLabel19.setText("Capacidad");

        jScrollPane2.setViewportView(txtCodigoActualizarCurso);

        jScrollPane3.setViewportView(txtRequisitoActualizarCurso);

        jScrollPane4.setViewportView(txtCapacidadActualizarCurso);

        cmdActualizarCurso.setText("Actualizar");
        cmdActualizarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarCursoActionPerformed(evt);
            }
        });

        cmbProgramasActualizar.setModel(listModelProgramas);
        cmbProgramasActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProgramasActualizarActionPerformed(evt);
            }
        });

        jLabel27.setText("Programa ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cmdActualizarCurso)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProgramasActualizar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProgramasActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdActualizarCurso)
                .addGap(24, 24, 24))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Estudiante");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setText("Ver");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "item otro añadido nuevo aja" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(txtCursos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel29.setText("Matricula");

        jLabel30.setText("RegCruso");

        jLabel15.setText("Asignar Nota ");

        jLabel16.setText("Actualizar Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel30)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegEstActionPerformed
        controlador.registrarEstudiante();
    }//GEN-LAST:event_btnRegEstActionPerformed

    private void btnCancelarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEstActionPerformed
        controlador.cancelarEstudiante();
    }//GEN-LAST:event_btnCancelarEstActionPerformed

    private void cmdRegCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegCursoActionPerformed
        controlador.registrarCurso();
    }//GEN-LAST:event_cmdRegCursoActionPerformed

    private void cmbProgramaAcadRegCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramaAcadRegCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProgramaAcadRegCursoActionPerformed

    private void cmbCodigoEstudianteMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodigoEstudianteMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCodigoEstudianteMatriculaActionPerformed

    private void cmbProgramaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramaMatriculaActionPerformed
        // TODO add your handling code here:
        controlador.programaSeleccionado();
    }//GEN-LAST:event_cmbProgramaMatriculaActionPerformed

    private void cmdActualizarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarCursoActionPerformed
        // TODO add your handling code here:
        controlador.actualizarCurso();
    }//GEN-LAST:event_cmdActualizarCursoActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void cmbCodigoCursoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodigoCursoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCodigoCursoMatriculaActionPerformed

    private void btnCancelarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCursoActionPerformed
        // TODO add your handling code here:
        controlador.desactivarCurso();
    }//GEN-LAST:event_btnCancelarCursoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdMatricularCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMatricularCursoActionPerformed
        // TODO add your handling code here:
        controlador.matricular();
    }//GEN-LAST:event_cmdMatricularCursoActionPerformed

    private void txtSemestreEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemestreEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemestreEstudianteActionPerformed

    private void cmdVerCursosEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerCursosEstudianteActionPerformed
        // TODO add your handling code here:
        controlador.verProgramas();
    }//GEN-LAST:event_cmdVerCursosEstudianteActionPerformed

    private void cmbCursoAsignarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoAsignarNotaActionPerformed
        // TODO add your handling code here:
        controlador.cursoSeleccionadoAsignarNotas();
    }//GEN-LAST:event_cmbCursoAsignarNotaActionPerformed

    private void cmdAsignarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAsignarNotaActionPerformed
        // TODO add your handling code here:
        controlador.registrarNotaEstudiante();
    }//GEN-LAST:event_cmdAsignarNotaActionPerformed

    private void cmbProgramasActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramasActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProgramasActualizarActionPerformed

    public DefaultComboBoxModel<String> getListModelEstudiantesCurso() {
        return listModelEstudiantesCurso;
    }

    public void setListModelEstudiantesCurso(DefaultComboBoxModel<String> listModelEstudiantesCurso) {
        this.listModelEstudiantesCurso = listModelEstudiantesCurso;
    }

    public JComboBox<String> getCmbProgramasActualizar() {
        return cmbProgramasActualizar;
    }

    public void setCmbProgramasActualizar(JComboBox<String> cmbProgramasActualizar) {
        this.cmbProgramasActualizar = cmbProgramasActualizar;
    }

    
    
    
    public JTextPane getTxtCapacidadActualizarCurso() {
        return txtCapacidadActualizarCurso;
    }

    public void setTxtCapacidadActualizarCurso(JTextPane txtCapacidadActualizarCurso) {
        this.txtCapacidadActualizarCurso = txtCapacidadActualizarCurso;
    }

    public JTextField getTxtCapacidadRegCurso() {
        return txtCapacidadRegCurso;
    }

    public void setTxtCapacidadRegCurso(JTextField txtCapacidadRegCurso) {
        this.txtCapacidadRegCurso = txtCapacidadRegCurso;
    }

    public JTextPane getTxtCodigoActualizarCurso() {
        return txtCodigoActualizarCurso;
    }

    public void setTxtCodigoActualizarCurso(JTextPane txtCodigoActualizarCurso) {
        this.txtCodigoActualizarCurso = txtCodigoActualizarCurso;
    }

    public JTextField getTxtCodigoCursoRegCurso() {
        return txtCodigoCursoRegCurso;
    }

    public void setTxtCodigoCursoRegCurso(JTextField txtCodigoCursoRegCurso) {
        this.txtCodigoCursoRegCurso = txtCodigoCursoRegCurso;
    }

    public JList<String> getTxtCursos() {
        return txtCursos;
    }

    public void setTxtCursos(JList<String> txtCursos) {
        this.txtCursos = txtCursos;
    }

    public JLabel getTxtLista() {
        return txtLista;
    }

    public void setTxtLista(JLabel txtLista) {
        this.txtLista = txtLista;
    }

    public JTextField getTxtNombreCursoRegCurso() {
        return txtNombreCursoRegCurso;
    }

    public void setTxtNombreCursoRegCurso(JTextField txtNombreCursoRegCurso) {
        this.txtNombreCursoRegCurso = txtNombreCursoRegCurso;
    }

    public JTextPane getTxtNota() {
        return txtNota;
    }

    public void setTxtNota(JTextPane txtNota) {
        this.txtNota = txtNota;
    }

    public JTextPane getTxtRequisitoActualizarCurso() {
        return txtRequisitoActualizarCurso;
    }

    public void setTxtRequisitoActualizarCurso(JTextPane txtRequisitoActualizarCurso) {
        this.txtRequisitoActualizarCurso = txtRequisitoActualizarCurso;
    }

    public JTextField getTxtRequisitoPromedioRegCurso() {
        return txtRequisitoPromedioRegCurso;
    }

    public void setTxtRequisitoPromedioRegCurso(JTextField txtRequisitoPromedioRegCurso) {
        this.txtRequisitoPromedioRegCurso = txtRequisitoPromedioRegCurso;
    }

    
    public JComboBox<String> getCmbListaCursos() {
        return cmbCodigoCursoMatricula;
    }

    public JComboBox<String> getCmbListaEstudiantes() {
        return cmbCodigoEstudianteMatricula;
    }

    public JComboBox<String> getCmbProgramaAcad() {
        return cmbProgramaAcadRegCurso;
    }

    public JTextField getSemestreEstudiante() {
        return txtSemestreEstudiante;
    }
    

    public void setSemestreEstudiante(JTextField semestreEstudiante) {
        this.txtSemestreEstudiante = semestreEstudiante;
    }

    public JTextField getTxtSemestreEstudiante() {
        return txtSemestreEstudiante;
    }

    public void setTxtSemestreEstudiante(JTextField txtSemestreEstudiante) {
        this.txtSemestreEstudiante = txtSemestreEstudiante;
    }
    
    

    public JTextField getTxtCapacidad() {
        return txtCapacidadRegCurso;
    }

    public JTextField getTxtCodigoCurso() {
        return txtCodigoCursoRegCurso;
    }

    public JTextField getTxtCodigoEstudiante() {
        return txtCodigoEstudiante;
    }

    public JTextField getTxtCorreoEstudiante() {
        return txtCorreoEstudiante;
    }

    public JTextField getTxtNombreCurso() {
        return txtNombreCursoRegCurso;
    }

    public JTextField getTxtNombreEstudiante() {
        return txtNombreEstudiante;
    }

    public JTextField getTxtPromedioEstudiante() {
        return txtPromedioEstudiante;
    }

    public JTextField getTxtRequisitoPromedio() {
        return txtRequisitoPromedioRegCurso;
    }

    public JTextField getTxtTelefonoEstudiante() {
        return txtTelefonoEstudiante;
    }

    public JComboBox<String> getCmbCodigoCursoMatricula() {
        return cmbCodigoCursoMatricula;
    }

    public void setCmbCodigoCursoMatricula(JComboBox<String> cmbCodigoCursoMatricula) {
        this.cmbCodigoCursoMatricula = cmbCodigoCursoMatricula;
    }

    public JComboBox<String> getCmbCodigoEstudianteMatricula() {
        return cmbCodigoEstudianteMatricula;
    }

    public void setCmbCodigoEstudianteMatricula(JComboBox<String> cmbCodigoEstudianteMatricula) {
        this.cmbCodigoEstudianteMatricula = cmbCodigoEstudianteMatricula;
    }

    public JComboBox<String> getCmbCursoAsignarNota() {
        return cmbCursoAsignarNota;
    }

    public void setCmbCursoAsignarNota(JComboBox<String> cmbCursoAsignarNota) {
        this.cmbCursoAsignarNota = cmbCursoAsignarNota;
    }

    public JComboBox<String> getCmbEstudianteAsignarNota() {
        return cmbEstudianteAsignarNota;
    }

    public void setCmbEstudianteAsignarNota(JComboBox<String> cmbEstudianteAsignarNota) {
        this.cmbEstudianteAsignarNota = cmbEstudianteAsignarNota;
    }

    public JComboBox<String> getCmbProgramaAcadRegCurso() {
        return cmbProgramaAcadRegCurso;
    }

    public void setCmbProgramaAcadRegCurso(JComboBox<String> cmbProgramaAcadRegCurso) {
        this.cmbProgramaAcadRegCurso = cmbProgramaAcadRegCurso;
    }

    public JComboBox<String> getCmbProgramaAsignarNota() {
        return cmbProgramaAsignarNota;
    }

    public void setCmbProgramaAsignarNota(JComboBox<String> cmbProgramaAsignarNota) {
        this.cmbProgramaAsignarNota = cmbProgramaAsignarNota;
    }

    public JComboBox<String> getCmbProgramaMatricula() {
        return cmbProgramaMatricula;
    }

    public void setCmbProgramaMatricula(JComboBox<String> cmbProgramaMatricula) {
        this.cmbProgramaMatricula = cmbProgramaMatricula;
    }

    public JButton getBtnCancelarCurso() {
        return btnCancelarCurso;
    }

    public void setBtnCancelarCurso(JButton btnCancelarCurso) {
        this.btnCancelarCurso = btnCancelarCurso;
    }

    public JButton getBtnCancelarEst() {
        return btnCancelarEst;
    }

    public void setBtnCancelarEst(JButton btnCancelarEst) {
        this.btnCancelarEst = btnCancelarEst;
    }

    
    public JButton getBtnRegEst() {
        return btnRegEst;
    }

    public void setBtnRegEst(JButton btnRegEst) {
        this.btnRegEst = btnRegEst;
    }

    public JButton getCmdActualizarCurso() {
        return cmdActualizarCurso;
    }

    public void setCmdActualizarCurso(JButton cmdActualizarCurso) {
        this.cmdActualizarCurso = cmdActualizarCurso;
    }

    public JButton getCmdAsignarNota() {
        return cmdAsignarNota;
    }

    public void setCmdAsignarNota(JButton cmdAsignarNota) {
        this.cmdAsignarNota = cmdAsignarNota;
    }

    public JButton getCmdMatricularCurso() {
        return cmdMatricularCurso;
    }

    public void setCmdMatricularCurso(JButton cmdMatricularCurso) {
        this.cmdMatricularCurso = cmdMatricularCurso;
    }

    public JButton getCmdRegCurso() {
        return cmdRegCurso;
    }

    public void setCmdRegCurso(JButton cmdRegCurso) {
        this.cmdRegCurso = cmdRegCurso;
    }

    public JButton getCmdVerCursosEstudiante() {
        return cmdVerCursosEstudiante;
    }

    public void setCmdVerCursosEstudiante(JButton cmdVerCursosEstudiante) {
        this.cmdVerCursosEstudiante = cmdVerCursosEstudiante;
    }

    public DefaultComboBoxModel<String> getListModelCursosMatriculados() {
        return listModelCursosMatriculados;
    }

    public void setListModelCursosMatriculados(DefaultComboBoxModel<String> listModelCursosMatriculados) {
        this.listModelCursosMatriculados = listModelCursosMatriculados;
    }

    public DefaultComboBoxModel<String> getListModelEstudiantes() {
        return listModelEstudiantes;
    }

    public void setListModelEstudiantes(DefaultComboBoxModel<String> listModelEstudiantes) {
        this.listModelEstudiantes = listModelEstudiantes;
    }

    public DefaultComboBoxModel<String> getListModelProgramas() {
        return listModelProgramas;
    }

    public void setListModelProgramas(DefaultComboBoxModel<String> listModelProgramas) {
        this.listModelProgramas = listModelProgramas;
    }
    
    
    
    
    
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatriculaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCurso;
    private javax.swing.JButton btnCancelarEst;
    private javax.swing.JButton btnRegEst;
    private javax.swing.JComboBox<String> cmbCodigoCursoMatricula;
    private javax.swing.JComboBox<String> cmbCodigoEstudianteMatricula;
    private javax.swing.JComboBox<String> cmbCursoAsignarNota;
    private javax.swing.JComboBox<String> cmbEstudianteAsignarNota;
    private javax.swing.JComboBox<String> cmbProgramaAcadRegCurso;
    private javax.swing.JComboBox<String> cmbProgramaAsignarNota;
    private javax.swing.JComboBox<String> cmbProgramaMatricula;
    private javax.swing.JComboBox<String> cmbProgramasActualizar;
    private javax.swing.JButton cmdActualizarCurso;
    private javax.swing.JButton cmdAsignarNota;
    private javax.swing.JButton cmdMatricularCurso;
    private javax.swing.JButton cmdRegCurso;
    private javax.swing.JButton cmdVerCursosEstudiante;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane txtCapacidadActualizarCurso;
    private javax.swing.JTextField txtCapacidadRegCurso;
    private javax.swing.JTextPane txtCodigoActualizarCurso;
    private javax.swing.JTextField txtCodigoCursoRegCurso;
    private javax.swing.JTextField txtCodigoEstudiante;
    private javax.swing.JTextField txtCorreoEstudiante;
    private javax.swing.JList<String> txtCursos;
    private javax.swing.JLabel txtLista;
    private javax.swing.JTextField txtNombreCursoRegCurso;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextPane txtNota;
    private javax.swing.JTextField txtPromedioEstudiante;
    private javax.swing.JTextPane txtRequisitoActualizarCurso;
    private javax.swing.JTextField txtRequisitoPromedioRegCurso;
    private javax.swing.JTextField txtSemestreEstudiante;
    private javax.swing.JTextField txtTelefonoEstudiante;
    // End of variables declaration//GEN-END:variables
}
